"""new fields: status flow, location, valve_type, report_type, attachments

Revision ID: 519fe92816b2
Revises: 922a67952157
Create Date: 2026-04-01 12:32:55.129328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '519fe92816b2'
down_revision = '922a67952157'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_attachment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=256), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['test_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('part_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('valve_type', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('valve_type_other', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('part_number', sa.String(length=64), nullable=True))

    with op.batch_alter_table('test_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('department', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('project', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('part_number', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('valve_type', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('valve_type_other', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('report_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('report_notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('estimated_delivery', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_shipped', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('date_parts_received', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_request', schema=None) as batch_op:
        batch_op.drop_column('date_parts_received')
        batch_op.drop_column('date_shipped')
        batch_op.drop_column('estimated_delivery')
        batch_op.drop_column('report_notes')
        batch_op.drop_column('report_type')
        batch_op.drop_column('valve_type_other')
        batch_op.drop_column('valve_type')
        batch_op.drop_column('part_number')
        batch_op.drop_column('project')
        batch_op.drop_column('department')
        batch_op.drop_column('location')

    with op.batch_alter_table('part_group', schema=None) as batch_op:
        batch_op.drop_column('part_number')
        batch_op.drop_column('valve_type_other')
        batch_op.drop_column('valve_type')
        batch_op.drop_column('location')

    op.drop_table('request_attachment')
    # ### end Alembic commands ###
