"""add user fields

Revision ID: 922a67952157
Revises: 
Create Date: 2026-04-01 10:15:55.285611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '922a67952157'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email_verified', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.add_column(sa.Column('verification_token', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')
        batch_op.drop_column('verification_token')
        batch_op.drop_column('email_verified')

    # ### end Alembic commands ###
