"""add accepting_requests flag to test_service

Revision ID: 9bf4f82f1e33
Revises: 85fc27df7fdf
Create Date: 2026-07-09 16:58:48.861123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bf4f82f1e33'
down_revision = '85fc27df7fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepting_requests', sa.Boolean(), nullable=False, server_default=sa.text('1')))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_service', schema=None) as batch_op:
        batch_op.drop_column('accepting_requests')

    # ### end Alembic commands ###
